# Generated by Django 4.1.3 on 2022-11-10 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('expiration', models.DateTimeField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrowed', to='users.user')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lent', to='users.user')),
            ],
        ),
    ]
